auth:
  basic_auth: false
  kerberos: true
  username: <Username>
  password: <Password>
board: <Board Name>
ca_cert_path: <Cert Path>
check_for_updates: 'false'
email_id: <Email ID>
git_urls:
- https://github.com/SatelliteQE/robottelo
- https://github.com/SatelliteQE/satellite6-upgrade
github_token: <Github Token>
github_username: <Github Username>
label_check: false
project: <Project Name>
url: <Jira URL>
verify_ssl: true
redmine_url: <redmine_url>
redmine_task_prefix: <redmine task prefix>
redmine_username: <redmine api username/email>
redmine_password: <redmine password>
