# Copy this file to /etc/jirasync/config.yaml or ~/.config/jirasync/config.yaml
auth:
  basic_auth: false
  kerberos: true
  username: <Username>
  password: <Password>
board: <Board Name>
ca_cert_path: <Cert Path>
check_for_updates: 'false'
email_id: <Email ID>
git_urls:
- https://github.com/SatelliteQE/robottelo
- https://github.com/SatelliteQE/satellite6-upgrade
github_token: <Github Token>
github_username: <Github Username>
label_check: false
project: <Project Name>
url: <Jira URL>
verify_ssl: true
redmine_url: <redmine_url>
redmine_task_prefix: <redmine task prefix>
redmine_username: <redmine api username/email>
redmine_password: <redmine password>
service:
  sleep_time: 120
  commands:
    - name: github
      kwargs:
        interval: week
        sync: true
    - name: redmine
      kwargs:
        sync: true
teams:
  SATQE:
      board: <Jira Board Name>
      email_id: <Email Id>
      git_urls:
      - https://github.com/SatelliteQE/robottelo
      - https://github.com/SatelliteQE/satellite6-upgrade
      github_token: <Git Hub Token>
      Users:
      #you can write all the users in mentioned below way
        Omkar Khatavkar:
          github_username: omkarkhatavkar
          jira_username: okhatavk
        Jitendra Yejare:
          github_username: jyejare
          jira_username: jyejare
  PulpQE:
      board: <Jira Board Name>
      email_id: <Email Id>
      git_urls:
      - https://github.com/SatelliteQE/robottelo
      - https://github.com/SatelliteQE/satellite6-upgrade
      github_token: <Git Hub Token>
      Users:
      #you can write all the users in mentioned below way
        Bruno Rocha:
          github_username: rochacbruno
          jira_username: brocha
          redmine_userid: 13998
        Brian herring:
          github_username: bherrin3
          jira_username: bherring
          redmine_userid: 14217
        Kersom Moura:
          github_username: kersommoura
          jira_username: kersom
          redmine_userid: 13606
